version: '3.8'

services:
  backend:
    container_name: skxx-web  # Замените на имя, определённое вашей группой, например, sk01-web
    build:
      context: ./backend
    ports:
      - "5000:5000"  # Замените на порт, определённый вашей группой
    volumes:
      - ./backend/logs:/usr/src/app/logs  # Монтирование логов бэкенда
    networks:
      - cdb-network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: my_db
      POSTGRES_HOST: db  # Имя сервиса базы данных для подключения

  frontend:
    container_name: skxx-frontend  # Замените на имя, определённое вашей группой, например, sk01-frontend
    build:
      context: ./frontend
    ports:
      - "80:80"  # Замените на порт, определённый вашей группой
    volumes:
      - ./frontend/logs:/var/log/nginx  # Монтирование логов фронтенда
    networks:
      - cdb-network

  db:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"  # Порт для доступа к PostgreSQL
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: my_db
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Персистентное хранилище данных
    networks:
      - cdb-network

  sql-client:
    image: dbeaver/cloudbeaver:latest
    container_name: skxx-sql-client  # Замените на имя, определённое вашей группой, например, sk01-sql-client
    ports:
      - "8081:8978"  # Порт для доступа к SQL-клиенту через браузер
    environment:
      CB_SERVER_HOST: "0.0.0.0"
      CB_SERVER_PORT: "8978"
    networks:
      - cdb-network

networks:
  cdb-network:
    external: true
    name: cdb-network

volumes:
  postgres-data:
