version: '3.8'

services:
  backend:
    container_name: sk10-web  # Nahraďte názvem definovaným vaší skupinou, například sk10-web
    build:
      context: ./backend
    ports:
      - "8009:8009"  # Nahraďte portem definovaným vaší skupinou
    volumes:
      - ./backend/logs:/usr/src/app/logs  # Připojení logů backendu
    networks:
      - cdb-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db  # Název databázové služby pro připojení

  frontend:
    container_name: sk10-frontend  # Nahraďte názvem definovaným vaší skupinou, například sk10-frontend
    build:
      context: ./frontend
    ports:
      - "3009:80"  # Nahraďte portem definovaným vaší skupinou
    volumes:
      - ./frontend/logs:/var/log/nginx  # Připojení logů frontend
    networks:
      - cdb-network

  db:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"  # Port pro přístup k PostgreSQL
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Trvalé úložiště dat
    networks:
      - cdb-network

  sql-client:
    image: dbeaver/cloudbeaver:latest
    container_name: sk10-sql-client  # Nahraďte názvem definovaným vaší skupinou, například sk10-sql-client
    ports:
      - "10009:8978"  # Port pro přístup k SQL klientovi prostřednictvím prohlížeče
    environment:
      CB_SERVER_HOST: "${CB_SERVER_HOST}"
      CB_SERVER_PORT: "${CB_SERVER_PORT}"
    networks:
      - cdb-network

networks:
  cdb-network:
    external: true
    name: cdb-network

volumes:
  postgres-data:
