version: '3.8'

services:
  backend:
    build:
      context: ./backend
    image: wea:backend
    ports:
      - "8009:8009"
    volumes:
      - ./backend:/app
      - ./backend/logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=postgresql://user:user@db:5432/mydb
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    image: wea:frontend
    ports:
      - "3009:3009"
    depends_on:
      - backend

  db:  # Služba pro PostgreSQL

    image: postgres:17
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
    ports:
      - "50009:5432"  # Exponovaný port databáze
    volumes:
      - pgdata:/var/lib/postgresql/data  # Uložení dat

  sql-client:
    image: dbeaver/cloudbeaver:latest
    ports:
      - "10009:8978"
    environment:
      CB_SERVER_HOST: "${CB_SERVER_HOST}"
      CB_SERVER_PORT: "${CB_SERVER_PORT}"
    depends_on:
      - db
volumes:
  pgdata:  # Definice persistentního volume
