version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - ./backend/logs:/usr/src/app/logs
    container_name: hello-backend

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend/logs:/var/log/nginx
    container_name: hello-frontend
