version: '3.8'

services:
  backend:
    container_name: sk10-web  # Nahraďte názvem definovaným vaší skupinou, například sk10-web
    build:
      context: ./backend
    ports:
      - "8009:8009"  # Nahraďte portem definovaným vaší skupinou
    volumes:
      - ./backend/logs:/usr/src/app/logs  # Připojení logů backendu
    networks:
      - cdb-network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: my_db
      POSTGRES_HOST: db  # Název databázové služby pro připojení

  frontend:
    container_name: sk10-frontend  # Nahraďte názvem definovaným vaší skupinou, například sk01-frontend
    build:
      context: ./frontend
    ports:
      - "3009:80"  # Nahraďte portem definovaným vaší skupinou
    volumes:
      - ./frontend/logs:/var/log/nginx  # Připojení logů frontend
    networks:
      - cdb-network

  db:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"  # Port pro přístup k PostgreSQL
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: my_db
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Trvalé úložiště dat
    networks:
      - cdb-network

  sql-client:
    image: dbeaver/cloudbeaver:latest
    container_name: sk10-sql-client  # Nahraďte názvem definovaným vaší skupinou, například sk01-sql-client
    ports:
      - "10009:8978"  # Port pro přístup k SQL klientovi prostřednictvím prohlížeče
    environment:
      CB_SERVER_HOST: "0.0.0.0"
      CB_SERVER_PORT: "8978"
    networks:
      - cdb-network

networks:
  cdb-network:
    external: true
    name: cdb-network

volumes:
  postgres-data:
