# docker-compose.yml
version: '3.8'

services:
  backend:
    container_name: sk10-web
    build:
      context: ./backend
    ports:
      - "8009:8009"
    volumes:
      - ./backend/logs:/usr/src/app/logs
      - ./backend/data_mock.csv:/usr/src/app/data_mock.csv  # Монтирование файла CSV
    networks:
      - cdb-network
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      IMPORT_CSV_ON_STARTUP: 'True'  # Переменная окружения для импорта CSV
    depends_on:
      - db

  frontend:
    container_name: sk10-frontend
    build:
      context: ./frontend
      args:
        - REACT_APP_API_URL=http://backend:8009  # Используем имя сервиса бэкенда
    ports:
      - "3009:80"
    volumes:
      - ./frontend/logs:/var/log/nginx
    networks:
      - cdb-network

  db:
    image: postgres:latest
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - cdb-network

  sql-client:
    image: dbeaver/cloudbeaver:latest
    container_name: sk10-sql-client
    ports:
      - "10009:8978"
    environment:
      CB_SERVER_HOST: "${CB_SERVER_HOST}"
      CB_SERVER_PORT: "${CB_SERVER_PORT}"
    networks:
      - cdb-network

networks:
  cdb-network:
    external: true
    name: cdb-network

volumes:
  postgres-data:
